name: deploy to a server on push
on: [push]
jobs:
  deploy-to-server:
    runs-on: ubuntu-latest
    steps:
      - run: |
     
      
         sshpass -p "kumbac4l4" scp -r https://github.com/Tomas-R/Task01-website tomas@164.132.173.129:/home/tomas/master


     # scp -P 59674   this/website/index.html tomas@164.132.173.129:/home/tomas/master
